//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekorasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gunler()
        {
            this.CalismaSaatleri = new HashSet<CalismaSaatleri>();
        }
    
        public int Id { get; set; }
        public string Gunler1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalismaSaatleri> CalismaSaatleri { get; set; }
    }
}
