//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekorasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Haber()
        {
            this.HaberGaleri = new HashSet<HaberGaleri>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Gorsel { get; set; }
        public string SEOLink { get; set; }
        public int Durum { get; set; }
        public int SiraNo { get; set; }
        public string Icerik { get; set; }
        public int HaberKategoriId { get; set; }
    
        public virtual HaberKategori HaberKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HaberGaleri> HaberGaleri { get; set; }
    }
}
