//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekorasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hizmet()
        {
            this.HizmetGaleri = new HashSet<HizmetGaleri>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public int SiraNo { get; set; }
        public int Durum { get; set; }
        public string Icerik { get; set; }
        public string Gorsel { get; set; }
        public string SEOLink { get; set; }
        public Nullable<int> HizmetKategoriId { get; set; }
    
        public virtual HizmetKategori HizmetKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HizmetGaleri> HizmetGaleri { get; set; }
    }
}
