//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekorasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IletisimForm
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Konu { get; set; }
        public string Icerik { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Durum { get; set; }
    }
}
