//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekorasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunGaleri
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Gorsel { get; set; }
        public int UrunId { get; set; }
        public int SiraNo { get; set; }
        public int Durum { get; set; }
    
        public virtual Urun Urun { get; set; }
    }
}
