//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekorasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.UrunGaleri = new HashSet<UrunGaleri>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Gorsel { get; set; }
        public string Icerik { get; set; }
        public string SEOLink { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public Nullable<int> Durum { get; set; }
        public int Hit { get; set; }
        public int KategoriId { get; set; }
    
        public virtual UrunKategori UrunKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunGaleri> UrunGaleri { get; set; }
    }
}
